name: Github Actions Demo

on:
  # on which type of events my workflow is triggered
  push:
jobs:
  # the name of the job
  jobname:
    # the display name of the job
    name: "display name"
    #runner
    runs-on:
      - ubuntu-latest
    # steps are thing that need to be done
    steps:
      - name: My first step
        run: |
          echo "Hello world"
      - name: MY second step
        run: |
          echo "second !"
  # running in parallel
  secondJob:
    name: "display the second"
    runs-on: ubuntu-latest
    steps:
      - name: My first step in the second job
        run: |
          echo "First second"
  thirdJob:
    name: "After job 1"
    runs-on: ubuntu-latest
    needs:
      - jobname
    steps:
      - name: Output from thirdjob
        run: echo "Hello jobname is over"
  forthJob:
    name: "After job 1"
    runs-on: ubuntu-latest
    needs:
      - jobname
    steps:
      - name: Output from forthjob 
        run: echo "Hello jobname is over"

  test:
    name: Test the frontend

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm ci
    - run: npm test
