name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{ github.event_name }}"
      - name: Liste file in repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job is ${{ job.status }}"