name: Github Actions Demo

on:
  # on which type of events my workflow is triggered
  push:
jobs:
  # the name of the job
  jobname:
    # the display name of the job
    name: "display name"
    #runner
    runs-on:
      - ubuntu-latest
    # steps are thing that need to be done
    steps:
      - name: Step One
        run: |
          echo "Hello world"
