name: Github Actions Demo

on:
  # on which type of events my workflow is triggered
  push:
jobs:

  frontend-test:
    name: Frontend - Testing step

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci
    
    - name: Run frontend tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
  
  frontend-next:
    name: 'After tests'
    runs-on: ubuntu-latest
    needs: 
      - frontend-test
    steps:
      - name: Output from forthjob 
        run: echo "Hello jobname is over"

  backend-test:
    name: Backend - Testing step

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java (JDK)
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Maven dependencies
      run: mvn clean install

    - name: Run backend tests
      run: mvn clean test

  backend-next:
    name: 'After tests'
    runs-on: ubuntu-latest
    needs: 
      - backend-test
    steps:
      - name: Output from forthjob 
        run: echo "Hello jobname is over"