name: Github Actions Demo

on:
  # on which type of events my workflow is triggered
  push:
jobs:
  # the name of the job
  jobname:
    # the display name of the job
    name: "display name"
    #runner
    runs-on:
      - ubuntu-latest
    # steps are thing that need to be done
    steps:
      - name: My first step
        run: |
          echo "Hello world"
      - name: MY second step
        run: |
          echo "second !"
  # running in parallel
  secondJob:
    name: "display the second"
    runs-on: ubuntu-latest
    steps:
      - name: My first step in the second job
        run: |
          echo "First second"
  thirdJob:
    name: "After job 1"
    runs-on: ubuntu-latest
    needs:
      - jobname
    steps:
      - name: Output from thirdjob
        run: echo "Hello jobname is over"
  forthJob:
    name: "After job 1"
    runs-on: ubuntu-latest
    needs:
      - jobname
    steps:
      - name: Output from forthjob 
        run: echo "Hello jobname is over"

  frontend-tests:
    name: Frontend - Testing step

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci
    
    - name: Run frontend tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

  backend-test:
    name: Backend - Testing step

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java (JDK)
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Maven dependencies
      run: mvn clean install

    - name: Run backend tests
      run: mvn clean test

      